---
all:
  children:
    rds_admin_servers:
      hosts:
        ec2_rds_admin:
          ansible_host: "{{ ec2_public_ip }}"
          ansible_user: ec2-user
          ansible_ssh_private_key_file: "{{ ssh_key_path }}"
          ansible_python_interpreter: /usr/bin/python3
