---
# RDS Connection Credentials
# IMPORTANT: Encrypt this file with ansible-vault:
#   ansible-vault encrypt vars/rds_credentials.yml
#
# To edit:
#   ansible-vault edit vars/rds_credentials.yml
#
# To run playbook with vault:
#   ansible-playbook playbooks/setup_mysql_rds.yml --ask-vault-pass

rds_host: "prod-rds-instance.ce9u8gyqms1d.us-east-1.rds.amazonaws.com"
rds_port: 3306
rds_user: "admin"
rds_password: "CHANGE_ME_SECURE_PASSWORD"  # Change this!
rds_database: "ecommerce"
